#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi
source "$PLUGIN_BASE_PATH/common/functions"

DOKKU_SYSLOG_ROOT="$DOKKU_ROOT/.syslog"
[[ -f "$DOKKU_SYSLOG_ROOT/OPTS" ]] && source "$DOKKU_SYSLOG_ROOT/OPTS"

dokku_syslog_docker_args() {
  local APP="$1"; local PROC_TYPE="$3"; local CONTAINER_INDEX="$4"; local docker_args STDIN
  local desc="dokku syslog docker args trigger"
  local SYSLOG_TAG=$APP
  [[ -n "$PROC_TYPE" ]] && SYSLOG_TAG+=".$PROC_TYPE"
  [[ -n "$CONTAINER_INDEX" ]] && SYSLOG_TAG+=".$CONTAINER_INDEX"

  SYSLOG_FORMAT=${SYSLOG_FORMAT:="rfc5424"}
  STDIN=$(cat)
  docker_args="$STDIN"
  [[ -n "${SYSLOG_SERVER}" ]] && docker_args+=" --log-driver syslog --log-opt syslog-address=${SYSLOG_SERVER} --log-opt tag=${SYSLOG_TAG} --log-opt syslog-format=${SYSLOG_FORMAT}"
  echo -n "$docker_args"
}

dokku_syslog_docker_args "$@"
